on:
  script:
    config:
      active: false
    run: |
      const result = await helpers.axios.get("https://m.gdfs.com/goods/243361.html");
      const result1 = await helpers.axios.get("https://m.gdfs.com/goods/215206.html");
      const text = result.data;
      const text1 = result1.data;
      if(text.includes("补货中") && text1.includes("补货中")){
        console.log("补货中");
        return [];
      }else{
        console.log("没补货");

        return [
          {
            id: new Date().getTime()
          }
        ];
      }
    deduplicationKey: id

jobs:
  ifttt:
    name: Make a Request to IFTTT
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            <b>gdfs页面状态有变化</b>
          format: html
          disable_web_page_preview: true
