on:
  rss:
    url:
      - https://rss.owenyoung.com/sale/douban-pin-group.xml
      - https://rss.owenyoung.com/sale/douban-driver-group.xml
      - https://rss.owenyoung.com/sale/douban-dog-group.xml
    config:
      active: false
      skipFirst: true

jobs:
  ifttt:
    name: Make a Request to IFTTT
    runs-on: ubuntu-latest
    steps:
      - uses: actionsflow/ifttt-webhook-action@v1
        with:
          event: doubansale
          key: ${{ secrets.IFTTT_KEY }}
          value1: ${{on.rss.outputs.title}}
          value2: ${{on.rss.outputs.contentSnippet}}
          value3: ${{on.rss.outputs.link}}
