on:
  rss:
    url: http://feed.smzdm.com/
    config:
      filterScript: |
        const title = item.title;
        if(title.includes('历史低价')){
          const keywords = ["罐头","狗粮","驱虫","牛奶","生鲜","三分钟","米诺","护发素","歌剧魅影","香水","螺蛳粉","米诺"];
          const notIncludeKeywords = ["求","付邮送","求购","交流","已购","专楼","闲置","讨论","停车","代拍","完","意向","封禁","避雷","支持","安踏","飞跃","蒙牛","华为","伊利","国产"]
          const isInclude = keywords.some((keyword)=>{
            return title.includes(keyword)
          })
          const isNotInclude = notIncludeKeywords.some((keyword)=>{
            return title.includes(keyword)
          })
          return isInclude && !isNotInclude
        }
      filterOutputs:
        title: 1
        link: 1
        contentSnippet: 1
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            <b>值得买: ${{ on.rss.outputs.title}}</b>
            <a href="${{on.rss.outputs.link}}">${{on.rss.outputs.contentSnippet}}</a>
          format: html
          disable_web_page_preview: true
