on:
  telegram_bot:
    token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    webhook: true
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          telegram_outputs: ${{ toJson(on.telegram_bot.outputs) }}
        run: |
          echo telegram: $telegram_outputs
      - name: Request
        uses: actionsflow/axios@v1
        with:
          url: https://b764fd50872214eafe0a3c92700c50c4.m.pipedream.net
          method: "POST"
          data: '{"text":"<<<${{on.telegram_bot.outputs.text}}>>>","from":"${{ on.telegram_bot.outputs.from.first_name }}"}'
